name: test

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: clone
        run: |
        git clone https://github.com/ant-design/ant-design 




