name: test
on: 
  push:
    branches: 
    - master


jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        run: |
        git clone https://github.com/ant-design/ant-design 




